/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#006d41",
        "error": "#ba1a1a",
        "surface-container": "#f0eee5",
        "on-error-container": "#93000a",
        "surface-tint": "#5f5e5e",
        "on-secondary-fixed-variant": "#005230",
        "on-surface-variant": "#3a4a3f",
        "inverse-surface": "#30312b",
        "surface-container-low": "#f6f4eb",
        "primary-container": "#e2dfde",
        "on-secondary": "#ffffff",
        "surface-variant": "#e4e3da",
        "secondary-fixed-dim": "#00e38d",
        "on-primary-fixed": "#1b1b1c",
        "primary-fixed-dim": "#c8c6c5",
        "error-container": "#ffdad6",
        "outline": "#6a7b6e",
        "on-tertiary-fixed": "#001a43",
        "secondary-fixed": "#55ffa9",
        "on-tertiary-fixed-variant": "#004398",
        "surface-dim": "#dcdad1",
        "on-primary": "#ffffff",
        "background": "#fbf9f0",
        "on-secondary-container": "#006d41",
        "tertiary": "#0059c6",
        "surface-container-high": "#eae8df",
        "primary": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d4dfff",
        "inverse-primary": "#c8c6c5",
        "inverse-on-surface": "#f3f1e8",
        "outline-variant": "#b9cbbc",
        "on-primary-fixed-variant": "#474746",
        "surface-container-highest": "#e4e3da",
        "on-secondary-fixed": "#002110",
        "on-background": "#1b1c17",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#636262",
        "tertiary-fixed": "#d9e2ff",
        "surface": "#fbf9f0",
        "on-surface": "#1b1c17",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-container": "#015dce",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f0",
        "secondary-container": "#00f99b",
        "tertiary-fixed-dim": "#afc6ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Space Grotesk"],
        "label": ["Space Grotesk"]
      },
      borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
